
const HosSpecialtiesList = [
    'Cardiology',
    'Neurology',
    'Orthopedics',
    'Pediatrics',
    'Oncology',
    'Gynecology and Obstetrics',
    'Dermatology',
    'Gastroenterology',
    'Urology',
    'Pulmonology',
    'Endocrinology',
    'Ophthalmology',
    'Psychiatry',
    'Rheumatology',
    'Nephrology',
    'Hematology',
    'Infectious Disease',
    'Radiology',
    'Anesthesiology',
    'Emergency Medicine'
  ];
  
  const HosFacilitiesList = [
    'Emergency Room',
    'Operating Room',
    'Intensive Care Unit (ICU)',
    'Laboratory Services',
    'Radiology Department',
    'Pharmacy',
    'Physical Therapy',
    'Maternity Ward',
    'Pediatric Ward',
    'Psychiatric Ward',
    'Outpatient Services',
    'Dialysis Center',
    'Ambulance Service',
    'Cafeteria',
    'Parking Facilities',
    'WiFi Access',
    'Wheelchair Accessible',
    'Language Interpretation Services',
    'Pet Therapy',
    'Chaplaincy Services',
    'Fitness Center',
    'Gift Shop',
    'Hospice Care',
    'Sleep Lab',
    'Blood Bank',
    'MRI Center',
    'CT Scan Center',
    'Endoscopy Suite',
    'Radiation Oncology',
    'Rehabilitation Services',
    'Neonatal Intensive Care Unit (NICU)',
    'Pediatric Intensive Care Unit (PICU)',
    'Burn Unit',
    'Hyperbaric Medicine',
    'Wound Care Center',
    'Birthing Center',
    'Memory Care',
    'Pain Management Clinic',
    'Vein Clinic',
    'Orthopedic Clinic',
    'Women’s Health Clinic',
    'Mental Health Clinic',
    'Urgent Care Center',
    'Allergy Clinic',
    'Dental Clinic',
    'Eye Clinic',
    'Travel Medicine Clinic',
    'Sleep Disorder Clinic',
    'Sports Medicine Clinic',
    'Occupational Health Clinic',
    'Diabetes Clinic',
    'Asthma Clinic',
    'Gastroenterology Clinic',
    'Neurology Clinic',
    'Oncology Clinic',
    'Cardiology Clinic',
    'Dermatology Clinic',
    'ENT Clinic',
    'Orthopedic Surgery Center',
    'Plastic Surgery Center',
    'Robotic Surgery Center',
    'Sports Medicine Center',
    'Vein Treatment Center',
    'Women’s Health Center',
    'Wound Care Center',
    'Breast Care Center',
    'Digestive Health Center',
    'Heart and Vascular Center',
    'Stroke Center',
    'Comprehensive Cancer Center',
    'Joint Replacement Center',
    'Rehabilitation Center',
    'Memory Disorders Center',
    'Pain Management Center',
    'Spine Center',
    'Allergy and Immunology Center',
    'Sleep Disorders Center',
    'Urgent Care Center'
  ];
  
  const HosServicesProvidedList = [
    'Emergency Care',
    'Primary Care',
    'Surgery',
    'Laboratory Services',
    'Radiology Services',
    'Pharmacy Services',
    'Maternity Care',
    'Pediatric Care',
    'Mental Health Services',
    'Rehabilitation Services',
    'Nutrition Services',
    'Dental Care',
    'Vision Care',
    'Orthopedic Services',
    'Cancer Treatment',
    'Cardiac Care',
    'Stroke Care',
    'Pain Management',
    'Home Health Services',
    'Hospice Care',
    'Telemedicine Services',
    'Specialty Clinics',
  ];
  const HosAccessibilityFeatures = [
    'Wheelchair',
    'Stretchers',
    'Rooms',
    'Ramps',
    'Elevators',
    'GrabBars',
    'Parking',
    'Doors',
    'Signage',
    'Restrooms',
    'Lifts',
    'EmergencyExits',
    'Handrails',
    'AccessibleTransport',
    'WaitingAreas',
    'SpecialistEquipment',
    'BrailleSignage',
    'AccessibleTechnology',
    'VisualAids',
    'Audiobooks',
    'InterpreterServices'
  ];


  const clinicSpecialties = [
    "Family Medicine",
    "Internal Medicine",
    "Pediatrics",
    "Geriatrics",
    "Cardiology",
    "Endocrinology",
    "Gastroenterology",
    "Hematology",
    "Infectious Diseases",
    "Nephrology",
    "Oncology",
    "Pulmonology",
    "Rheumatology",
    "General Surgery",
    "Orthopedic Surgery",
    "Cardiothoracic Surgery",
    "Neurosurgery",
    "Plastic Surgery",
    "Vascular Surgery",
    "Obstetrics and Gynecology",
    "Reproductive Endocrinology and Infertility",
    "Gynecologic Oncology",
    "Psychiatry",
    "Psychology",
    "Counseling",
    "General Dermatology",
    "Dermatopathology",
    "Cosmetic Dermatology",
    "General Neurology",
    "Pediatric Neurology",
    "Neurophysiology",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Sports Medicine",
    "Radiology",
    "Pathology",
    "Laboratory Services",
    "Allergy and Immunology",
    "Anesthesiology",
    "Pain Management",
    "Podiatry",
    "Urology",
    "Ophthalmology",
    "Otolaryngology (ENT)",
    "Sleep Medicine",
    "Emergency Medicine",
    "Chiropractic",
    "Acupuncture",
    "Nutrition",
    "Holistic Medicine",
    "Weight Management",
    "Diabetes Clinic",
    "Hypertension Clinic",
    "Travel Medicine",
    "Adolescent Medicine",
    "HIV/AIDS Clinic",
    "Wound Care"
  ];
  const clinicaccessibilityFeatures = [
    "Ramps",
    "AutomaticDoors",
    "Elevators",
    "Restrooms",
    "Braille",
    "TactileIndicators",
    "Handrails",
    "Parking",
    "WideDoorways",
    "AdjustableTables",
    "ReceptionDesks",
    "HearingLoops",
    "VRS",
    "TTY",
    "Websites",
    "Alerts",
    "ServiceAnimals",
    "Interpreters",
    "Transportation",
    "MobilityEquipment",
    "LoweredCounters",
    "Signage",
    "ListeningDevices",
    "Seating",
    "EvacuationPlans",
    "DisabilityAwareness",
    "HomeVisits",
    "ExamRooms",
    "EscortServices",
    "Showers",
    "Telehealth",
    "VisualAids",
    "PortableRamps",
    "Pathways",
    "Fountains",
    "DropOffAreas",
    "Lighting",
    "Kitchenettes",
    "PatientLifts",
    "Chairs",
    "Workstations",
    "Intercoms",
    "CommunicationBoards",
    "MultiformatInfo",
    "EducationMaterials"
  ];
  const clinicFacilities = [
    "Waiting Area",
    "Reception Desk",
    "Consultation Rooms",
    "Examination Rooms",
    "Operating Theaters",
    "Diagnostic Imaging Center (X-ray, MRI, CT scan)",
    "Laboratory Services",
    "Pharmacy",
    "Physical Therapy Room",
    "Occupational Therapy Room",
    "Counseling Rooms",
    "Emergency Room",
    "Minor Procedure Room",
    "Vaccination Center",
    "Children's Play Area",
    "Restrooms",
    "Cafeteria or Refreshment Area",
    "Administrative Offices",
    "Medical Records Department",
    "IT Support and Data Center",
    "Parking Lot",
    "Ambulance Service",
    "Medical Supply Store",
    "Telemedicine Facilities",
    "Patient Education Center",
    "Fitness and Wellness Center",
    "In-house Pharmacy",
    "Recovery Rooms",
    "Day Care Surgery Unit",
    "Wound Care Center",
    "Chiropractic Care Room",
    "Acupuncture Room",
    "Holistic Medicine Room",
    "Infusion Center",
    "IV Therapy Rooms",
    "Dialysis Center",
    "Sleep Study Rooms",
    "Audiology Booth",
    "Optometry Exam Room",
    "ENT Examination Room",
    "Dermatology Procedure Room",
    "Dental Clinic",
    "Radiation Therapy Room",
    "On-site Laboratory",
    "Blood Bank",
    "Infection Control Room",
    "Sterilization Room",
    "Medical Waste Disposal Facility",
    "Staff Lounge",
    "Conference Room",
    "Patient Counseling and Support Services",
    "Health Screening and Check-up Center"
  ];
  const clinicservicesProvidedList = [
    "General Medical Consultations",
    "Specialist Consultations",
    "Preventive Health Screenings",
    "Vaccinations and Immunizations",
    "Chronic Disease Management",
    "Women's Health Services",
    "Prenatal and Postnatal Care",
    "Pediatric Care",
    "Geriatric Care",
    "Mental Health Services",
    "Counseling and Therapy",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Therapy",
    "Nutritional Counseling",
    "Weight Management Programs",
    "Diabetes Education and Management",
    "Hypertension Management",
    "Cardiac Rehabilitation",
    "Smoking Cessation Programs",
    "Minor Surgical Procedures",
    "Wound Care",
    "IV Therapy",
    "Infusion Services",
    "Dialysis Services",
    "Radiology Services (X-ray, MRI, CT scan, Ultrasound)",
    "Laboratory Services",
    "Pharmacy Services",
    "Telemedicine Consultations",
    "Emergency Care",
    "Travel Medicine Services",
    "Allergy Testing and Treatment",
    "Asthma Management",
    "Dermatology Services",
    "Cosmetic Procedures",
    "Orthopedic Services",
    "Pain Management Services",
    "Rehabilitation Services",
    "Sleep Studies",
    "Audiology Services",
    "Eye Examinations and Treatments",
    "ENT Services",
    "Dental Services",
    "Cancer Screening and Treatment",
    "HIV/AIDS Services",
    "Sexual Health Services",
    "Substance Abuse Counseling and Treatment",
    "Health Education and Promotion",
    "Support Groups",
    "Home Health Care Services",
    "Patient Transportation Services",
    "Fitness and Wellness Programs",
    "Acupuncture",
    "Chiropractic Care",
    "Holistic and Alternative Medicine",
    "Palliative and Hospice Care",
    "On-site Blood Bank",
    "Medical Records Management",
    "Health Insurance Assistance",
    "Occupational Health Services"
  ];
  
export  {
  clinicservicesProvidedList,
  clinicFacilities,
  clinicSpecialties,
  clinicaccessibilityFeatures,
    HosAccessibilityFeatures,
    HosFacilitiesList,
    HosServicesProvidedList,
    HosSpecialtiesList,
};